Removed .env requirement

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,7 +10,7 @@ die() {
 BASEDIR="$(dirname "$(readlink -f "$0")")"
 echo "Script Dir: $BASEDIR"
 
-[ -f "$BASEDIR/.env" ] || die ".env is required"
+# [ -f "$BASEDIR/.env" ] || die ".env is required"
 
 echo "Updating systemd scripts"
 sudo cp "$BASEDIR/systemd-unit/credfeto-package-cache.service" /etc/systemd/system/
