More robust mk-nuget-config

diff --git a/mk-nuget-config b/mk-nuget-config
--- a/mk-nuget-config
+++ b/mk-nuget-config
@@ -1,3 +1,17 @@
 #! /bin/sh
+
+PROG=$0
+die() {
+    echo
+    echo "$@"
+    exit 1
+}
+
+BASEDIR="$(dirname "$(readlink -f "$0")")"
+
+SOURCE="$BASEDIR/nuget.config"
+
+[ -f "$SOURCE" ] || die "Could not find $SOURCE"
+
 rm ~/.nuget/NuGet/NuGet.Config
-ln -s $(pwd)/nuget.config ~/.nuget/NuGet/NuGet.Config
+ln -s "$SOURCE" "$HOME/.nuget/NuGet/NuGet.Config"
