Compose profile

diff --git a/update b/update
--- a/update
+++ b/update
@@ -31,6 +31,13 @@ if [ ! -f "$BASEDIR/.env" ]; then
   } > "$BASEDIR/.env"
 fi
 
+echo "Using $BASEDIR/.env"
+. "$BASEDIR/.env"
+
+echo "COMPOSE_PROFILE: $COMPOSE_PROFILE"
+
+[ -z "$COMPOSE_PROFILE" ] && COMPOSE_PROFILE=full
+
 sudo chown -R 10001:65533 /cache/npm || die "Could not set npm permissions"
 sudo chown -R 1654:1654 /cache/nuget || die "Could not set nuget permissions"
 sudo chown -R 1654:1654 /cache/proxy || die "Could not set proxy permissions"
@@ -107,6 +114,6 @@ sudo docker volume create \
 
 sudo docker compose pull || die "Could not pull images"
 
-sudo docker compose up -d --remove-orphans || die "Could not start containers"
+sudo docker compose --profile "$COMPOSE_PROFILE" up -d --remove-orphans || die "Could not start containers"
 
 
