Logging

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,10 +1,22 @@
 #! /bin/sh
 
+die() {
+    echo
+    echo "$@"
+    exit 1
+}
+
+
 [ -d /cache/nginx ] || sudo mkdir /cache/nginx
 [ -d /cache/npm ] || sudo mkdir /cache/npm
 [ -d /cache/nuget ] || sudo mkdir /cache/nuget
 
 git pull
 
-sudo chown -R 10001:65533 /cache/npm
-sudo docker compose pull && docker compose build && sudo docker compose up -d
+sudo chown -R 10001:65533 /cache/npm || die "Could not set npm permissions"
+
+sudo docker compose pull || die "Could not pull images"
+sudo docker compose build || die "Could not build images"
+sudo docker compose up --no-start || die "Could not build containers"
+
+sudo docker compose up -d --remove-orphans || die "Could not start containers"
