linux-musl

diff --git a/cache/populate b/cache/populate
--- a/cache/populate
+++ b/cache/populate
@@ -215,7 +215,7 @@ installDotNet() {
      echo "*       Current SDK: $SDK_VERSION"
      echo "**********************************************************************************************"
      echo ""
-     echo "Download $PROXY_HOST/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-x64.tar.gz"
+     echo "Download $PROXY_HOST/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-musl-x64.tar.gz"
      echo " to $TEMPORARY_FILE"
      curl --max-time 10 \
           --retry 5 \
@@ -225,7 +225,7 @@ installDotNet() {
           -L \
           -f \
           "$PROXY_HOST/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-x64.tar.gz" \
-          -o "$TEMPORARY_FILE" || die "Could not download: $PROXY_HOST/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-x64.tar.gz"
+          -o "$TEMPORARY_FILE" || die "Could not download: $PROXY_HOST/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-musl-x64.tar.gz"
 
      [ -f "$TEMPORARY_FILE" ] || die "Temp file not downloaded"
      extract_dotnet_package "$TEMPORARY_FILE" "/usr/share/dotnet" || die "Could not install"
